### ISSUE TITLE
[Experiment] Número de hilos y progreso de la ejecución

### ISSUE THREAD

**Issue by gualbe** [gualbe/weka-feature-selection-studio#1]
He establecido 8 hilos de ejecución, pero solo usa 4. Revisar si se tiene en cuenta correctamente el número de hilos. 

Por otra parte, la barra de progreso no muestra porcentajes intermedios. Pasa de 0% a 100% de golpe cuando termina el proceso completo.

He probado con esta configuración y datasets:

<img width="1452" alt="Captura de Pantalla 2022-08-18 a las 12 04 33" src="https://user-images.githubusercontent.com/13599751/185369959-b0016996-0d72-48f6-93ef-cc75e2b7efeb.png">

**Comment by AndresManuelCH** [comment]
En cuanto al número de hilos para el proceso de ejecución, de ello se encarga un objeto executor de la clase ExecutorService, como puede verse en la captura que pongo de ejemplo, del campo textField se recibe correctamente el número de hilos indicado. Y el objeto executor tiene correctamente seteado dichos valores (corePoolSize y maximumPoolSize):

![image](https://user-images.githubusercontent.com/48735306/185390514-c02017b1-2498-44d2-8a8d-52a261b277fb.png)

En cuanto al progreso de la barra de ejecución, eso ocurre porque a la barra de ejecución sólo se le pueden pasar números enteros, en el momento en el cual el número de objetos sobrepasa a 100 (el máximo progreso de dicha barra), a cada hilo se le asigna un valor de finalización menor a 1. Cuando este valor es muy cercano a 1, ocurre un redondeo y la barra de progreso continua (aunque como es obvio, en estos casos se tiene en cuenta que no llegue a 100 hasta que todos hayan terminado), pero cuando es bastante más bajo a 1 (por ejemplo, si hay 300 objetos), a cada hilo se le asigna un valor muy pequeño, pero al finalizar, la barra de progreso coge este valor como 0. Al final se realiza una comprobación de si han terminado todos, y se pone a 100 instantáneamente (de ahí que pasa de 0 a 100 del tirón).
