### ISSUE TITLE
[Results] No aparecen los resultados de los tests estadísticos

### ISSUE THREAD

**Issue by gualbe** [gualbe/weka-feature-selection-studio#2]
He probado con esta configuración:

<img width="1452" alt="Captura de Pantalla 2022-08-18 a las 12 04 33" src="https://user-images.githubusercontent.com/13599751/185371055-0c9d3f2b-773e-4329-b757-ec92a78e1c6c.png">

Y en la pestaña de resultados no aparecen los tests estadísticos:

<img width="1453" alt="Captura de Pantalla 2022-08-18 a las 12 04 26" src="https://user-images.githubusercontent.com/13599751/185371218-7058e9aa-c22a-4ac1-b700-c720693df589.png">

Puede que esté relacionado con que muchas métricas F-measure en la tabla de métricas están a NaN (lo pongo como otra issue). O puede que esté relacionado con que conecta bien con el intérprete de Python.

**Comment by AndresManuelCH** [comment]
Se debe a que en los sistemas Unix, las barras de direcciones en las rutas son "/" cuando en Windows son "\". También interfería que en los nombres de los archivos de métricas estaban puesto las barras sin ser necesarias. Esto queda solucionado.
