### ISSUE TITLE
[Results] Métricas a NaN

### ISSUE THREAD

**Issue by gualbe** [gualbe/weka-feature-selection-studio#3]
Usando esta configuración:

<img width="1452" alt="Captura de Pantalla 2022-08-18 a las 12 04 33" src="https://user-images.githubusercontent.com/13599751/185372020-c5ccbef5-808e-43c3-99b5-5c221c81a783.png">

Obtengo muchos valores de la métrica F-measure a NaN. Lo mismo con Recall, Precisión, AUC y MCC. Accuracy y Kappa van bien, sin embargo, tiene todos sus valores:

<img width="1453" alt="Captura de Pantalla 2022-08-18 a las 12 04 26" src="https://user-images.githubusercontent.com/13599751/185371919-c503c397-9a98-4930-bb18-6a0fdc44cb56.png">

**Comment by AndresManuelCH** [comment]
Ocurre porque al calcular las métricas correspondientes a cada combinación, en el caso de CV, se realiza un sumatorio de las métricas pertenecientes a los objetos de esa combinación (en el caso de ejemplo, 10 objetos resultados para cada combinación). Pero, no se comprobaba que al realizar este sumatorio alguna vez diese NaN, en el momento en el cual una era NaN, dicho sumatorio pasaba a ser NaN. Esto ocurre con aquellas métricas que dependen de una clase positiva, por ello, con Accuracy y Kappa iba bien. Ya está solucionado (pongo de ejemplo sólo con los datasets minefield05 y minefield25 para ahorrarme tiempo de ejecución):

![image](https://user-images.githubusercontent.com/48735306/185389264-ffddc890-853b-4d30-8d9f-3f2e54f0c2d8.png)
